### PR TITLE
Additions

### PR DESCRIPTION
**Pull request by wynwxst**
sry if u don't know me but i found this an interesting project so i decided to help, if u don't wanna accept then sure...

# Changes:

1. added ban and unban with shortcuts
2. implemented working echo/say/shout cmd

### CODE REVIEW

**Comment by OtakuStan** [comment]
We welcome all contributions so thanks for contributing to the project. Our internal Team will be reviewing your code before merging the pull request.
Team OtakuStan

**Comment by OtakuStan** [comment]
@Lunaticsatoshi Please look into it

**Review by Lunaticsatoshi — APPROVED** [review]

**Comment by Lunaticsatoshi** [comment]
Works fine we will modify some lines but the contribution will remain intact.

**Comment by wynwxst** [comment]
ok

**Pull request merged**
